### ISSUE TITLE
pi-hole upstream out of date

### ISSUE THREAD

**Issue by weitzner** [juampe/docker-pi-hole-dot#3]
Thanks for putting together this image - I use it and it works well. Are you planning to pull the upstream pihole image to update this? It would be great if this generally kept pace with upstream.

**Comment by weitzner** [comment]
It looks like the docker hub image isn't syncing up with the pi-hole upstream - is this still something that needs to be done manually?

**Comment by juampe** [comment]
I just add a dispatch event to CI, to manually trigger the build process.
